version: "3.9"

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
      - redis
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: always
    networks:
      - monitoring

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - zipkin
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: [ "vault", "server", "-config=/vault/config/config.hcl" ]
    volumes:
      - vault-data:/vault/file
      - ./vault-config:/vault/config
    networks:
      - monitoring

volumes:
  grafana-data:
  redis-data:
  prometheus-data:
  vault-data:

networks:
  monitoring:
